### ISSUE TITLE
running with error

### ISSUE THREAD

**Issue by adhioutlined** [igormp/Imp#3]
installing this themes and get this error, every running in command : 
```
┌─[r2d2][xwing:~][%]
└─▪whoami
r2d2
battery:1: command not found: plugged_in                                                                                    
battery:3: command not found: battery_pct
battery:[:3: unknown condition: -gt
battery:6: command not found: battery_pct
┌─[r2d2][xwing:~][%]
└─▪
```

**Comment by igormp** [comment]
That error is due to a bug in oh-my-zsh that I tried to fix with [this simple commit](https://github.com/robbyrussell/oh-my-zsh/pull/6207/commits/bd8fdbf782cdae67e47c8cffd0f86a50b8af8531), but it looks like it hasn't been merged.

I'm actually thinking about removing the battery level indicator, since it has brought some problems and doing so would solve this problem. What do you think?

**Comment by igormp** [comment]
I've removed the battery % status, which should fix this error.

**Comment by adhioutlined** [comment]
nice.... thanks for the update 👍
